# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aleksanderblaszkiewicz
service: ray-tracer-unit

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

functions:
  main:
    timeout: 30
    handler: dist/lambda-main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
